// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCartService.Data;

#nullable disable

namespace ShoppingCartService.Migrations
{
    [DbContext(typeof(ShoppingCartContext))]
    [Migration("20221012000530_shoppingCartMigration")]
    partial class shoppingCartMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoppingCartService.Models.Item", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("productId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("shoppingcartId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("shoppingcartId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ShoppingCartService.Models.ShoppingCart", b =>
                {
                    b.Property<string>("shoppingcartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("purchaseId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shoppingcartId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("ShoppingCartService.Models.Item", b =>
                {
                    b.HasOne("ShoppingCartService.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("items")
                        .HasForeignKey("shoppingcartId");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("ShoppingCartService.Models.ShoppingCart", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
