// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Data;

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OrderService.Models.Address", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("OrderService.Models.Bill", b =>
                {
                    b.Property<string>("billingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("issueDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("sum")
                        .HasColumnType("float");

                    b.HasKey("billingId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("OrderService.Models.Order.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("billingAddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("billingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deliveryAddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("orderStatus")
                        .HasColumnType("int");

                    b.Property<double>("sum")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.HasIndex("billingAddressId");

                    b.HasIndex("deliveryAddressId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("OrderService.Models.Order.Order", b =>
                {
                    b.HasOne("OrderService.Models.Address", "billingAddress")
                        .WithMany()
                        .HasForeignKey("billingAddressId");

                    b.HasOne("OrderService.Models.Address", "deliveryAddress")
                        .WithMany()
                        .HasForeignKey("deliveryAddressId");

                    b.Navigation("billingAddress");

                    b.Navigation("deliveryAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
